### ISSUE TITLE
getting 401 Client Error: Unauthorized for url: https://www.pinterest.com/resource/UserSessionResource/create/ 

### ISSUE THREAD

**Issue by DrunkCodes** [bstoilov/py3-pinterest#106]
Am getting this error while trying to login a list of accounts.

Some of the accounts where logged in because the folders where created, then some where not this error came up
the total number of the accounts is 24.
401 Client Error: Unauthorized for url: https://www.pinterest.com/resource/UserSessionResource/create/
this is my code
`def multi_login():
    for accts in section_b:
        pinterest = Pinterest(email=accts[0],
                              password=accts[1],
                              username=accts[2],
                              cred_root='')
        pinterest.login()

multi_login()`

**Comment by bstoilov** [comment]
Related to 
https://github.com/bstoilov/py3-pinterest/issues/108

**Comment by bstoilov** [comment]
See if version 1.2.1 solves your problems

**Comment by Carnagency** [comment]
I have tried a lot of the things that were discussed in all the different conversations of the repositery.

I was really hopeless and I found that it was simply due to me living in a non-english country so I just had to change the settings of my pinterest account and put US in country and american english in language.

Check this link out :

https://docs.contentstudio.io/article/497-pinterest-post-failed-to-publish#:~:text=Authorization%20Problem%3A%20If%20you%20are,the%20account%20to%20the%20English.

Also try to suppress the content of cred_root so that it fills up with updated and working data.
Hope this will help some fellow coders !
