### ISSUE TITLE
The login, repin and comment  is not working for now

### ISSUE THREAD

**Issue by DrunkCodes** [bstoilov/py3-pinterest#107]
Login:
        I tried to login it keep sending 429 error code saying too many request from the url . with just one or two request it will start sending the 429 error code.

repin:
         it's sending 401 error code saying unauthorized url

commenting: 
          it send this pinJsonData = json.loads(s.contents[0])['resources']['data']['PinResource']
KeyError: 'resources'

Yesterday everything was working fine but now it all crash.

Also I have being looking for a way to use py3-pinterest with multiple accounts like 24-50 accts. please I would appreciate your advice on the best practices.

**Comment by kruvatz** [comment]
workaround for login: initialize Pinterest instance via _pinterest_sess

i see that they now care about recaptchaV3Token attribute when log in.
it successfully login when recaptchaV3Token given

**Comment by bstoilov** [comment]
Yes they included captcha. Apparently the project is getting famous and they are trying to counter us.

I will have to switch to web driver login, I can't break the google captcha. Will keep you updated

**Comment by DrunkCodes** [comment]
I will be waiting for an update to the code

**Comment by DrunkCodes** [comment]
@kruvatz please can you share how you bypass the recapatcha

**Comment by bstoilov** [comment]
@DrunkCodes @kruvatz

https://github.com/bstoilov/py3-pinterest/tree/login-with-selenium

I implemented webdirver login, can you guys checkout my branch and see if it works?
Locally on my machine I see no errors

**Comment by DrunkCodes** [comment]
@bstoilov how do I get it to my system

**Comment by bstoilov** [comment]
@DrunkCodes you have to checkout the code.

**Comment by bstoilov** [comment]
Anyways if that is not possible for you atm don't worry. 
I will have to do more testing before I push it in pypi. I will try to do it by tomorrow, since this is probably affecting all users

**Comment by DrunkCodes** [comment]
Will I be able to use it with multiple accounts like 25 to 50 accts. @bstoilov

**Comment by bstoilov** [comment]
@DrunkCodes 
I have just published the new version 1.2.1

Can you try it and see if it solves your problems?

As for the 25-50 accounts. I have nevery used more than 10. I tested locally with 3-4 accounts before releasing, just make sure use use proxies.

Also I am not entierly sure how `pinterest.login(proxy='ip_address:port')` will work with your proxies, but you should use up to 3 accounts per IP.
https://www.blackhatworld.com/seo/how-many-account-on-pinterest-per-ip.640754/
People recommend 2, but I use 3 without problems

**Comment by DrunkCodes** [comment]
Thanks@bstoilov  for the account advise. I will check it see if the problems have gone

**Comment by DrunkCodes** [comment]
@bstoilov  I can add the proxy parameter at the first calling of Pinterest (email, password, username, proxy)
I think it will work better they. Also how do I make each acct have it's own object

**Comment by bstoilov** [comment]
I have put it there because in the first calling the proxies can be a list and the client will autorotate them. But you are right that it is a bit inconvinient like this.

As for the other question. Each account can have its own object if you just create it, the only heave operation is login, other than that you can even create new pinterest object every time you use it and it won't cause any problems.

**Comment by bstoilov** [comment]
All of the issues above will be solved with the login fixes
I just created this one https://github.com/bstoilov/py3-pinterest/issues/120

**Comment by Carnagency** [comment]
I have tried a lot of the things that were discussed in all the different conversations of the repositery.

I was really hopeless and I found that it was simply due to me living in a non-english country so I just had to change the settings of my pinterest account and put US in country and american english in language.

Check this link out :

https://docs.contentstudio.io/article/497-pinterest-post-failed-to-publish#:~:text=Authorization%20Problem%3A%20If%20you%20are,the%20account%20to%20the%20English.

Also try to suppress the content of cred_root so that it fills up with updated and working data.
Hope this will help some fellow coders !
