### ISSUE TITLE
Follow people/boards based on keywords

### ISSUE THREAD

**Issue by austkel** [bstoilov/py3-pinterest#12]
Can you follow boards and people in batch based on keywords?

**Comment by austkel** [comment]
I have a few specific questions/requests about the program. My Skype is: chronos.ventures
Don't mind paying for your time.

**Comment by bstoilov** [comment]
You can search with scope 'users' or 'boards' and then use follow or follow board methods. Refer to the readme and exaplex.py

**Comment by austkel** [comment]
Okay if you use the search command how do you use that in conjunction with the invite function to pass the data returned through.

**Comment by bstoilov** [comment]
If you want to follow boards, you need to use the search function with `scope=boards`
If you want to follow users you need to use `scope=pins` and then extract pinner from each pin. (This is due to recent changes in pinterest api that remove the users scope from the search.)

To follow a board you should use `follow_board` method
To follow user the `follow` method

I created an example python file with the logic above.

https://github.com/bstoilov/py3-pinterest/blob/master/follow_examples.py
