### ISSUE TITLE
How to find board ID?

### ISSUE THREAD

**Issue by austkel** [bstoilov/py3-pinterest#14]
How to find board ID?

**Comment by bstoilov** [comment]
Hi,

```
boards = []
board_batch = pinterest.boards()
while len(board_batch) > 0:
    boards += board_batch
    board_batch = pinterest.boards()

for b in boards:
    print(b)
```

This code saves all boards into the boards variable.

Each board object has the following structure:

{'id': '<id>', 'name': '<name>', 'url': '/<username>/<board-name-url>/', 'description': '<description>', 'pin_count': <number>, 'privacy': '<public|private>'}

It is implemented in such manner because pinterest returns everything in batches of specific size, so you can just tell then give me all the boards, instead you need to make multiple calls to obtain all the batches.
