### ISSUE TITLE
Every function that uses POST method arises this error "requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:...."

### ISSUE THREAD

**Issue by housUnus** [bstoilov/py3-pinterest#143]
The functions with get method work fine but when i try to use a function with the post method it arises this error: 
"requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:...."

**Comment by aaqibmehrban** [comment]
same here

**Comment by MiguelAHentoux** [comment]
same here

**Comment by bstoilov** [comment]
Make sure you are properly logged in, the script has to create a credentials dir with few tokens inside when login is successful

**Comment by Carnagency** [comment]
I have tried a lot of the things that were discussed in all the different conversations of the repositery.

I was really hopeless and I found that it was simply due to me living in a non-english country so I just had to change the settings of my pinterest account and put US in country and american english in language.

Check this link out :

https://docs.contentstudio.io/article/497-pinterest-post-failed-to-publish#:~:text=Authorization%20Problem%3A%20If%20you%20are,the%20account%20to%20the%20English.

Also try to suppress the content of cred_root so that it fills up with updated and working data.
Hope this will help some fellow coders !
