### ISSUE TITLE
Can't use pinterest.pin()

### ISSUE THREAD

**Issue by LudmilaBash** [bstoilov/py3-pinterest#47]
Can't create new pin with pinterest.pin()
**Scenario 1** with pinterest.login():
I get error.
HTTPError: 401 Client Error: Unauthorized for url: https://www.pinterest.com/resource/PinResource/create/

**Scenario 2** without using pinterest.login() but Pinterest is opened in browser and I am logged in to my account:
No error but I don't see the pin.

**Comment by LudmilaBash** [comment]
Any ideas? What to do?

**Comment by bstoilov** [comment]
Hello sorry for the late reply.

Your browser session has nothing to do with the pinterest client.

The python client is unable to obtain valid session with pinterest. Please double check the credentials you are providing to the login method, also make sure you are using the latest version of the client. https://pypi.org/project/py3-pinterest/

One more thing how do you login in to pinterest typically? Are you by any chance using social login? Currently you can use the client with social login accounts.

**Comment by Carnagency** [comment]
I have tried a lot of the things that were discussed in all the different conversations of the repositery.

I was really hopeless and I found that it was simply due to me living in a non-english country so I just had to change the settings of my pinterest account and put US in country and american english in language.

Check this link out :

https://docs.contentstudio.io/article/497-pinterest-post-failed-to-publish#:~:text=Authorization%20Problem%3A%20If%20you%20are,the%20account%20to%20the%20English.

Also try to suppress the content of cred_root so that it fills up with updated and working data.
Hope this will help some fellow coders !
