### ISSUE TITLE
download images script doesn;t work

### ISSUE THREAD

**Issue by bstoilov** [bstoilov/py3-pinterest#75]

**Comment by Visualieyes** [comment]
On line 38, in the body of the for loop, replace the code with the following. 

Note*: It was weird. After revising it, I ran the code a few times and still got errors because of indentation, even though there were none. But after playing around with the spacing and re-saving the program it eventually just worked.

try:
		url = pin['images']['orig']['url']
		indx = str(url).rfind('.')
		extension = str(url)[indx:]
		download_image(url, download_dir + pin['id'] + extension)

	except KeyError as e:
		break

**Comment by bstoilov** [comment]
This was resolved
